In [7]:
import numpy as np

In [9]:
sample = np.array([1,2,3,4,5])
sample * 5

array([ 5, 10, 15, 20, 25])

In [11]:
2+8*5

42

Array Types and Conversions between Types

In [14]:
integers = np.array([10,20,30,40,50])

In [16]:
print(integers)

[10 20 30 40 50]


In [18]:
integers[0]

10

In [20]:
integers[0] = 20

In [22]:
integers

array([20, 20, 30, 40, 50])

In [24]:
integers[0] = 21.5

In [26]:
integers

array([21, 20, 30, 40, 50])

In [28]:
integers.dtype

dtype('int32')

In [29]:
smallerIntegers=np.array(integers, dtype=np.int8)
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [30]:
integers.nbytes

20

In [34]:
smallerIntegers.nbytes

5

In [35]:
floats = np.array([1.2,2.3,3.4,5.6,8.1])

In [36]:
floats

array([1.2, 2.3, 3.4, 5.6, 8.1])

MULTIDIMENSIONAL ARRAYS

In [38]:
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [40]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
nums[0,0]

1

In [45]:
nums[1,4]

10

In [48]:
nums.ndim # two dimensional array

2

In [49]:
multi_arr = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])

In [51]:
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
multi_arr[1,0,2] # the 1 equivalent in next two dimensional array and the rows of 0 and the columns of 2

9

CREATING ARRAYS FROM LISTS AND OTHER PYTHON STRUCTURES

In [56]:
first_list = [1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [58]:
first_array=np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
second_lisst = [1,2,3,-1.23,50,128000.56,4.56]
second_array = np.array(second_lisst)

In [62]:
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [64]:
second_array.dtype

dtype('float64')

In [68]:
third_list = ['Ann', 111111, 'Peter',11112,'Susan',11113, 'John',11114]

In [69]:
third_array = np.array(third_list)
third_array

array(['Ann', '111111', 'Peter', '11112', 'Susan', '11113', 'John',
       '11114'], dtype='<U11')

In [71]:
first_tuple = (5,10,15,20,25,30)
array_from_tuple = np.array(first_tuple)
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [73]:
array_from_tuple.dtype

dtype('int32')

In [74]:
multi_dim_list = [[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]]
array_from_multi_dim_list = np.array(multi_dim_list)
array_from_multi_dim_list

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

INTRISIC NumPy array Creation

In [79]:
integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
integers_second_array = np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [83]:
integers_third_array = np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [84]:
# numpy.linspace

In [85]:
first_floats_arr = np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [86]:
second_floats_arr = np.linspace(10,20,5)
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [87]:
first_rand_arr = np.random.rand(10) # random floats numbers in array
first_rand_arr

array([0.44720242, 0.79798522, 0.21974144, 0.39684925, 0.39171436,
       0.41526648, 0.46800048, 0.89721392, 0.95520963, 0.90980909])

In [88]:
second_rand_arr = np.random.rand(4,4)
second_rand_arr

array([[0.25361957, 0.81598999, 0.29446701, 0.02243583],
       [0.32922818, 0.40694969, 0.34760646, 0.88854402],
       [0.73164254, 0.02309722, 0.42567817, 0.94930145],
       [0.5713831 , 0.13919125, 0.05193396, 0.29696298]])

In [89]:
third_rand_arr = np.random.randint(0,100,20)
third_rand_arr

array([ 5, 16, 16, 55, 60, 54, 70, 58, 89, 96, 59, 27, 26, 37, 38, 91, 17,
       70,  2, 56])

CREATE ARRAYS FILLED WITH CONSTANT VALUES

In [94]:
first_z_array = np.zeros(5) # zeros in array
first_z_array

array([0., 0., 0., 0., 0.])

In [95]:
second_z_array = np.zeros((4,5))
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
first_ones_array = np.ones(6) # ones in array
first_ones_array

array([1., 1., 1., 1., 1., 1.])

In [101]:
second_ones_array = np.ones((7,8))
second_ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [102]:
third_ones_array = np.ones((4,5), dtype=int)
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [103]:
first_fill_array = np.empty(10, dtype=int) # init empty array
first_fill_array.fill(12) # fill with 12 in array
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [105]:
first_full_array = np.full(5,10) # the rows, the value
first_full_array

array([10, 10, 10, 10, 10])

In [106]:
second_full_array = np.full((4,5),8) # the rows & columns  and the value = 8

In [108]:
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

FIND THE SHAPE AND SIZE OF AN ARRAY

In [116]:
first_arr = np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [117]:
second_arr = np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [119]:
third_arr = np.full((2,2,2),10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [120]:
np.shape(first_arr) # the total in tuples 

(20,)

In [121]:
np.shape(second_arr) # columns and rows (10,2)

(10, 2)

In [122]:
np.shape(third_arr)

(2, 2, 2)

In [126]:
np.size(first_arr) # size of first_arr

20

In [128]:
np.size(second_arr) # size of second_arr

20

In [131]:
np.size(third_arr)

8

ADDING, REMOVING AND SORTING ELEMENTS

In [135]:
first_arr = np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [137]:
new_first_arr = np.insert(first_arr, 3,4) # inserting the arrays to new array, replace if the number is exist
new_first_arr

array([1, 2, 3, 4, 5])

In [138]:
second_arr = np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [141]:
new_second_arr = np.append(second_arr, [5,6,7]) # append the second_arr with the number of 5
new_second_arr

array([1, 2, 3, 4, 5, 6, 7])

In [142]:
third_arr = np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [144]:
del_arr = np.delete(third_arr, 4) # deleting the 4 in third_arr
del_arr

array([1, 2, 3, 4])

In [145]:
integers_arr = np.random.randint(0,20,20)
integers_arr

array([12, 18, 16, 19, 12,  5, 12,  0,  4, 18,  4,  2, 11,  1,  2,  6,  7,
        7, 18, 17])

In [148]:
print(np.sort(integers_arr))

[ 0  1  2  2  4  4  5  6  7  7 11 12 12 12 16 17 18 18 18 19]


In [151]:
integers_2dim_arr = np.array([[3,2,5,7,4],[5,0,8,3,1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [153]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [154]:
colors = np.array(['orange','green','yellow','white','black','pink','blue','red'])
colors

array(['orange', 'green', 'yellow', 'white', 'black', 'pink', 'blue',
       'red'], dtype='<U6')

In [157]:
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']


COPY AND VIEWS

In [161]:
students_ids_number = np.array([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [162]:
students_ids_number_reg = students_ids_number

In [165]:
print("id of students_ids_number", id(students_ids_number))
print("id of students_ids_number_reg", id(students_ids_number_reg))

id of students_ids_number 2501246592144
id of students_ids_number_reg 2501246592144


In [167]:
students_ids_number_reg[1] = 2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [168]:
students_ids_number_cp = students_ids_number.copy() # to copy the students_ids_number
print(students_ids_number_cp)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [169]:
print(students_ids_number_cp == students_ids_number)

[ True  True  True  True  True  True  True  True]


In [171]:
print("id of students_ids_number", id(students_ids_number))
print("id of students_ids_number_cp", id(students_ids_number_cp))

id of students_ids_number 2501246592144
id of students_ids_number_cp 2501246594928


In [174]:
students_ids_number[0] = 1000
print("original: ", students_ids_number)
print("copy: ", students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


In [176]:
students_ids_number_v = students_ids_number.view() #check the view

In [178]:
students_ids_number_v[0] = 2000
print("original: ", students_ids_number)
print("views: ", students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
views:  [2000 2222 1313 1414 1515 1616 1717 1818]


In [180]:
print(students_ids_number_cp.base) # check if the array is own the data if not return NONE
print(students_ids_number_v.base)

None
[2000 2222 1313 1414 1515 1616 1717 1818]


RESHAPING ARRAYS

In [184]:
first_arr = np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [186]:
second_arr = np.reshape(first_arr, (3,4)) # reshaping the arrays to multidimensional by typing rows,columns
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [188]:
third_arr = np.reshape(first_arr, (6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [189]:
# showing error if cannot reshape array of size 

In [192]:
fifth_arr = np.reshape(first_arr, (3,2,2))
print(fifth_arr)
print("Dimensions of fifth_arr is", fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr is 3


In [194]:
sixth_arr = np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [196]:
seventh_arr_flat = np.reshape(sixth_arr, -1) # create one dimensional array
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [198]:
eighth_arr_flat = sixth_arr.flatten() # flatten the arrays
print("eighth_arr_flat:", eighth_arr_flat)
ninth_arr_rav = sixth_arr.ravel() 
print("ninth_arr_rav:", ninth_arr_rav)

eighth_arr_flat: [1 2 3 4 5 6]
ninth_arr_rav: [1 2 3 4 5 6]


In [200]:
eighth_arr_flat[0]=100
ninth_arr_rav[0] = 200

In [202]:
print("eighth_arr_flat: ", eighth_arr_flat)
print("ninth_arr_rav:", ninth_arr_rav)

eighth_arr_flat:  [100   2   3   4   5   6]
ninth_arr_rav: [200   2   3   4   5   6]


INDEXING AND SLICING

In [204]:
twodim_arr = np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [206]:
twodim_arr[1,1]

5

In [208]:
twodim_arr[1]

array([4, 5, 6, 7])

In [211]:
threedim_arr = np.reshape(np.arange(3*4*5), (3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [212]:
threedim_arr[0,2,3] # indexing

13

In [215]:
 threedim_arr[2,-1,-1]

59

In [217]:
# slicing (start, stop, step)

In [219]:
onedim_arr = np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [223]:
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [225]:
onedim_arr[-3:]

array([7, 8, 9])

In [227]:
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [229]:
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [247]:
twodim_arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [253]:
twodim_arr[1,:] # in rows

array([4, 5, 6, 7])

In [255]:
twodim_arr[:,2] # in columns

array([ 2,  6, 10])

JOINING AND SPLITTING ARRAYS

In [258]:
# concatenate

In [260]:
first_arr = np.arange(1,11)
second_arr = np.arange(11,21)
print("first_arr: ", first_arr)
print("second_arr: ",second_arr)

first_arr:  [ 1  2  3  4  5  6  7  8  9 10]
second_arr:  [11 12 13 14 15 16 17 18 19 20]


In [264]:
con_arr = np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [266]:
third_2_darr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
third_2_darr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [268]:
fourth_2darr = np.array([[11,12,13,14,15],[16,17,18,19,20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [316]:
con2d_arr = np.concatenate((third_2_darr,fourth_2darr),axis=1)
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [286]:
st_arr = np.stack((first_arr,second_arr)) # create 2 dimensional array
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [288]:
hst_arr = np.hstack((first_arr,second_arr)) # create a single dimension
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [290]:
vst_arr = np.vstack((first_arr,second_arr)) 
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [292]:
# Splitting Arrays

In [294]:
fifth_arr = np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [298]:
sp_arr = np.array_split(fifth_arr,4) # split array in 4
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [300]:
print(sp_arr[1])

[4 5 6]


In [302]:
sp_arr = np.array_split(fifth_arr,8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [310]:
hs_arr = np.hsplit(third_2_darr,5)
hs_arr

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [312]:
vs_arr = np.vsplit(third_2_darr,2)
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

ARITHMTIC OPERATIONS AND FUNCTIONS

In [319]:
# High performing code, less verbose code, better maintainability

In [321]:
# ADD, SUB, MULTIPLY, DIV

In [323]:
a = np.arange(1,11)
b = np.arange(21,31)
print("a",a)
print("b",b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [325]:
a + b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [327]:
b -a 

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [329]:
a * b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [331]:
b / a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [333]:
c= np.arange(2,12)
print("c",c)

c [ 2  3  4  5  6  7  8  9 10 11]


In [335]:
a ** c

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192])

In [337]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [339]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [341]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [343]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [345]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [347]:
np.power(a,b) # exponent

array([          1,     4194304,  -346101685,           0,   167814181,
       -1543503872,    17998615,           0, -1635065239,  1073741824])

In [349]:
np.mod(b,a) # remainders

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [351]:
np.power(a,c)

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192])

In [355]:
np.sqrt(a) # square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

BROADCASTING

In [358]:
# describes how NumPy treats arrays with different shapes during arithmetic operations.

In [360]:
# Dimension Are Compatible, if their axes on a one-by-one basis, they have either the same length or a length of one

In [364]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [366]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [368]:
a + b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [374]:
c = np.arange(1,3) # because this is not compatible
c

array([1, 2])

In [372]:
a + c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [378]:
d = np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [380]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [382]:
d - e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

 AGGREGATE FUNCTIONS

In [385]:
first_arr = np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [387]:
second_arr = np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [391]:
third_arr = np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [393]:
first_arr.sum()

550

In [395]:
second_arr.sum()

450

In [397]:
third_arr.sum()

550

In [399]:
second_arr.sum(axis=0) # each column axis=0 column

array([120, 150, 180])

In [401]:
second_arr.sum(axis=1) # each row axis=1 rows

array([ 60, 150, 240])

In [403]:
first_arr.prod()

1704722432

In [405]:
second_arr.prod()

-1786839040

In [407]:
third_arr.prod()

1704722432

In [409]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [411]:
np.average(first_arr)

55.0

In [413]:
np.average(second_arr)

50.0

In [415]:
np.average(third_arr)

55.0

In [417]:
np.min(first_arr)

10

In [419]:
np.max(first_arr)

100

In [421]:
np.mean(first_arr) # plus all data and divide the length

55.0

In [423]:
np.std(first_arr) 

28.722813232690143

HOW TO GET UNIQUE ITEMS AND COUNTS

In [430]:
first_arr = np.array([1,2,3,4,5,6,1,2,2,1,10,7,8])
first_arr

array([ 1,  2,  3,  4,  5,  6,  1,  2,  2,  1, 10,  7,  8])

In [432]:
np.unique(first_arr) # get all unique numbes in array

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [438]:
second_arr = np.array([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [442]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [444]:
np.unique(second_arr, axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [446]:
np.unique(second_arr,axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [448]:
np.unique(first_arr, return_index=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5, 11, 12, 10], dtype=int64))

In [450]:
np.unique(second_arr,return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1], dtype=int64))

TRANSPOSE LIKE OPERATIONS

In [455]:
first_2dimarr = np.arange(12).reshape((3,4))
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [459]:
np.transpose(first_2dimarr) # transpose the array, meaning all columns goes to rows

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [461]:
second_2dimarr=np.arange(6).reshape(3,2)
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [471]:
np.transpose(second_2dimarr,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [473]:
first_3dimarr=np.arange(24).reshape(2,3,4)
first_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [475]:
np.moveaxis(first_3dimarr,0,-1) # , source, destination

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [477]:
np.swapaxes(first_3dimarr,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

REVERSING AN ARRAY

In [482]:
arr_1dim = [10,1,9,2,8,3,7,4,6,5]
arr_1dim

[10, 1, 9, 2, 8, 3, 7, 4, 6, 5]

In [484]:
arr_1dim[::-1]

[5, 6, 4, 7, 3, 8, 2, 9, 1, 10]

In [486]:
np.flip(arr_1dim) # reversing array 

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [490]:
arr_2dim=np.arange(9).reshape(3,3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [492]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [494]:
np.flip(arr_2dim,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [496]:
arr_3dim = np.arange(24).reshape(2,3,4)
arr_3dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [498]:
np.flip(arr_3dim,2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])

In [500]:
np.flip(arr_3dim,1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])